# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'golden' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for golden keystore

  node_modules_path = '../node_modules'
  rn_path = "../node_modules/react-native"
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTCameraRoll',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'react-native-golden-keystore', path: '../Libs/react-native-golden-keystore'
  # End pods for golden keystore
  
  pod 'react-native-camera', path: "#{node_modules_path}/react-native-camera"
  pod 'ReactNativeFabric', path: "#{node_modules_path}/react-native-fabric"
  pod 'react-native-fcm', path: "#{node_modules_path}/react-native-fcm"
  pod 'rn-golden-loading', path: '../Libs/rn-golden-loading'

  # React native permmission
  permissions_path = '../node_modules/react-native-permissions/ios'


  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"

  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'Mixpanel'

  pod 'react-native-shimmer', :path => "#{node_modules_path}/react-native-shimmer"

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end


